### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by hageningrid** [karenhompland/snequence#12]

**Comment by karenhompland** [comment]
Changes done:
- BOOM to bomb exploding
- Small scaling up and down to game objects in main game scene for more life in the game
- The bombs are slightly rotating 
- The hearts are "pumping" showing the user that this is nice to get
- When 2x score power up is in use there is a 2x symbol besides the score
- When there is three seconds or less again on the timer, it turns red. If more time is added, it turns green again.
