### ISSUE TITLE
Make new folder structure to adhere to MVC pattern

### ISSUE THREAD

**Issue by solveigua** [karenhompland/snequence#31]
View: scenes
Model: objectscripts
Controller: all script controllers

**Comment by karenhompland** [comment]
Tried this, but resulted in different conflicts and problems with prefabs and materials. Considering how we have worked woth this project and that we did not know anything about Unity before we started, we decided that we won't use MVC as our structure works nice as it is. The current structure is clear and easy to understand. As the code is not too complex and we do not have that many elements in the game at once, our current structure should be sufficient.
